# Generated by Django 5.2.4 on 2025-07-11 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone_number',
        ),
    ]
