# Generated by Django 5.2.4 on 2025-07-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_examsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
